final_space = true
console_title = false
console_template = "..."

[[lines]]
alignment = "left"

[[lines.module]]
name = "kubectl"
template = "<fg=000000;bg=ffea00> \uFD31 {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}</>"

[[lines]]
alignment = "left"
new_line = true

[[lines.module]]
name = "session"
template = """{{ if .IsRoot }}<fg=ffea00;bg=2f2f2f> \uF0E7 </><fg=ffea00;bg=2f2f2f> \ue0b1 </>{{ end }}
<fg=ffea00;bg=2f2f2f>{{ .UserName }}{{ if .IsSSHSession }}@{{.ComputerName}}{{ end }}</><fg=ffea00;bg=2f2f2f> \ue0b1 </>"""

[[lines.module]]
name = "path"
template = "<fg=ffea00;bg=2f2f2f> \ue5ff </><fg=fafafa;bg=2f2f2f>{{.Path}} </>"
aliases = { home = "\uF7DB " }
length = 2

[[lines.module]]
name = "git"
template = """<fg=ffea00;bg=2f2f2f> \ue0b1 </>{{ if .Detached}}<fg=ffea00;bg=red>{{ else}}<fg=ffea00;bg=2f2f2f>{{ end }}
  {{ .Branch }}
{{ if ne .Tag "" }}{{ .Tag }}{{ end }}
{{ if .Staged }} \uf044 {{ .Staged }}{{ end }}
{{ if .Conflicts }} \uf071 {{ .Conflicts }}{{ end }}
{{ if .Changed }} \uf046 {{ .Changed }}{{ end }}
{{ if .Untracked }} ~ {{ .Untracked }}{{ end }}
{{ if gt .Stashes 0 }} \uf692 {{ .Stashes }}{{ end }}</>
"""
fetch_stash_count = true
fetch_status = true

[[lines.module]]
name = "execTime"
template = "{{ if gt .Time 0}}<fg=ffea00;bg=2f2f2f> \ue0b1 </><fg=fafafa;bg=2f2f2f>{{.Value}} </>{{ end }}"

[[lines.module]]
name = "text"
template = " <fg=ffea00>\u276F</>"
