name: Release
on:
  release:
    types: [created]
jobs:
  release:
    name: Build release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ 'darwin', 'windows', 'freebsd', 'netbsd', 'openbsd' ]
        arch: [ 'amd64' ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - run: go build -o release/prompt-line-$GOOS-$GOARCH
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'release/prompt-line-*'
  release-linux:
    name: Build release binaries for linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ 'amd64', 'arm64', 'arm' ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - run: go build -o release/prompt-line-$GOOS-$GOARCH
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'release/prompt-line-*'
  release-themes:
    name: Build themes zip file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Zip theme files
        run: |
          $compress = @{
            Path = "theme/*.*"
            CompressionLevel = "Fastest"
            DestinationPath = "./release/themes.zip"
          }
          Compress-Archive @compress
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'release/themes.zip'